version: "3"
services:

    jekyll:
        image: jekyll/builder
        volumes:
            - ./jekyll/site:/srv/jekyll
            - ./jekyll/bundle:/usr/local/bundle

        command: >
            sh -c "bundle update && bundle exec jekyll serve . --watch"

        environment:
            - JEKYLL_UID=50011
            - HTTP_PROXY=http://172.17.0.1:8118 
            - HTTPS_PROXY=http://172.17.0.1:8118

    nginx:
        image: nginx
        ports:
            - "9002:80"
        volumes:
            - ./jekyll/site/_site:/usr/share/nginx/html

